name: Deploy to windows server

on:
  push:
    branches:
      - master


jobs:
  deploymenjob:
    name: Deploy to windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy to windows server
        run: | 
         sshpass -p "${{secrets.ADMIN_PASSWORD}}" \ 
          scp -o StrictHostKeyChecking=no qasim.html \
          "${{secrets.ADMIN_USERNAME}}"@${{secrets.SERVER_IP}}:"C:\inetpub\wwwroot\"
